[build]
command = "bun run build"
output_directory = "build"

[build.environment]
PUB_ENV = "production"
PUB_HOSTNAME = "myconverter.com"
PUB_PLAUSIBLE_URL = ""
PUB_VERTD_URL = "https://vertd.vert.sh"

[site]
bucket = "./build" 